[tool.poetry]
name = "isolation-similarity-forest"
version = "0.1.0"
description = "reaserch project developing new tool for outlier detection."
authors = ["SebChw <sebastian.chwilczynski@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "isolation_similarity_forest"}]

[tool.poetry.dependencies]
python = "^3.8"
scikit-learn = "^1.1.2"


[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.4"
black = "^22.10.0"
tox-poetry = "^0.4.1"
pytest = "^7.1.3"
pytest-mock = "^3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
