name: GitHub on push check
run-name: ${{ github.actor }} is testing out RISF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Install tox and any other packages
        run: pip install tox
      - name: Install depedencies from risf
        run: pip install -r requirements/requirements.txt
      - name: Install dev dependencies
        run: pip install -r requirements/requirements_dev.txt
      - name: Install RISF
        run: poetry run pip install -e .
      - name: Run tests
        run: poetry run python -m pytest
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
